import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from "next/font/google"
import Footer from '@/components/Footer'

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-mont bg-light dark:bg-dark w-full min-h-screen`}>
      <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
